export const CERTIFICATE_ENTER_DURATION_SECONDS = 1.05;
export const CERTIFICATE_EXIT_DURATION_SECONDS = 1.05;

export const CERTIFICATE_ENTER_DURATION_MS =
  CERTIFICATE_ENTER_DURATION_SECONDS * 1000;
export const CERTIFICATE_EXIT_DURATION_MS =
  CERTIFICATE_EXIT_DURATION_SECONDS * 1000;
